# Generated by Django 2.1.2 on 2019-03-08 19:36

from django.db import migrations, models
import django.db.models.deletion
import parler.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('G', 'General'), ('T', 'Talk'), ('P', 'Performance'), ('W', 'Workshop'), ('H', 'Hosting')], max_length=1, verbose_name='Type')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='activities/', verbose_name='Image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.Activity')),
            ],
            options={
                'verbose_name': 'activity Translation',
                'db_table': 'program_activity_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, verbose_name='Website or social media profile')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to='presenters/', verbose_name='Image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PresenterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('first', models.CharField(max_length=255, verbose_name='First name')),
                ('last', models.CharField(max_length=255, verbose_name='Last name')),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('quote', models.CharField(blank=True, max_length=255, verbose_name='Inspirational quote')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.Presenter')),
            ],
            options={
                'verbose_name': 'presenter Translation',
                'db_table': 'program_presenter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='presenters',
            field=models.ManyToManyField(to='program.Presenter'),
        ),
        migrations.AlterUniqueTogether(
            name='presentertranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='activitytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
