# Generated by Django 2.1.2 on 2018-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('T', 'Talk'), ('P', 'Performance'), ('W', 'Workshop'), ('H', 'Hosting')], max_length=1, verbose_name='Type')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255, verbose_name='First name')),
                ('last', models.CharField(max_length=255, verbose_name='Last name')),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('quote', models.CharField(blank=True, max_length=255, verbose_name='Inspirational quote')),
                ('link', models.URLField(blank=True, verbose_name='Website or social media profile')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='presenters',
            field=models.ManyToManyField(to='program.Presenter'),
        ),
    ]
