# Generated by Django 2.1.2 on 2019-03-12 21:22

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='image_shadows',
            field=versatileimagefield.fields.VersatileImageField(default=0, height_field='image_height', upload_to='presenters/', verbose_name='Image', width_field='image_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenter',
            name='image_shadows_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='presenter',
            name='image_shadows_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
