# Generated by Django 2.1.2 on 2019-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20190312_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='presenter',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
