# Generated by Django 2.1.2 on 2018-11-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20181113_2330'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='presenter',
            managers=[
            ],
        ),
    ]
