# Generated by Django 2.1.7 on 2019-03-26 23:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20190319_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='presenters/', verbose_name='Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='image_shadows',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='presenters/', verbose_name='Image', width_field='image_width'),
        ),
    ]
