# Generated by Django 2.1.2 on 2018-11-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20181113_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceManager',
        ),
        migrations.DeleteModel(
            name='TalkManager',
        ),
        migrations.DeleteModel(
            name='WorkshopManager',
        ),
    ]
