# Generated by Django 2.1.2 on 2019-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20181206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('G', 'General'), ('T', 'Talk'), ('P', 'Performance'), ('W', 'Workshop'), ('H', 'Hosting')], max_length=1, verbose_name='Type'),
        ),
    ]
