# Generated by Django 2.1.2 on 2019-02-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20190117_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('first', models.CharField(max_length=255, verbose_name='First name')),
                ('last', models.CharField(max_length=255, verbose_name='Last name')),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('quote', models.CharField(blank=True, max_length=255, verbose_name='Inspirational quote')),
            ],
            options={
                'verbose_name': 'presenter Translation',
                'db_table': 'program_presenter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='first',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='last',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='presentertranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.Presenter'),
        ),
        migrations.AlterUniqueTogether(
            name='presentertranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
