# Generated by Django 2.1.2 on 2019-03-04 11:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20190221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='activities/', verbose_name='Image', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to='presenters/', verbose_name='Image', width_field='image_width'),
        ),
    ]
