# Generated by Django 2.1.2 on 2019-03-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20190304_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'activity Translation',
                'db_table': 'program_activity_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.AddField(
            model_name='activitytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.Activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activitytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
