# Generated by Django 2.1.2 on 2018-11-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(choices=[('XP', 'Experience'), ('IT', 'IT'), ('FR', 'Fundraising'), ('GR', 'Graphics'), ('MD', 'Media'), ('SP', 'Speakers'), ('VP', 'Venue & Production')], max_length=2)),
            ],
        ),
    ]
