# Generated by Django 2.1.2 on 2019-03-08 19:45

from django.db import migrations, models
import django.db.models.deletion
import parler.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(choices=[('experience', 'Experience'), ('it', 'IT'), ('fundraising', 'Fundraising'), ('graphics', 'Graphics'), ('media', 'Media'), ('speakers', 'Speakers'), ('venue-production', 'Venue & Production')], max_length=16)),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to='team/', verbose_name='Image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_fun', versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to='team/', verbose_name='Image', width_field='image_width')),
                ('image_fun_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_fun_width', models.PositiveIntegerField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamMemberTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('first', models.CharField(max_length=255, verbose_name='First name')),
                ('last', models.CharField(max_length=255, verbose_name='Last name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='team.TeamMember')),
            ],
            options={
                'verbose_name': 'team member Translation',
                'db_table': 'team_teammember_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='teammembertranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
