# Generated by Django 2.1.2 on 2019-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
