# Generated by Django 2.1.2 on 2018-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20181206_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
