# Generated by Django 2.1.2 on 2019-02-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20181206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(choices=[('experience', 'Experience'), ('it', 'IT'), ('fundraising', 'Fundraising'), ('graphics', 'Graphics'), ('media', 'Media'), ('speakers', 'Speakers'), ('venue-production', 'Venue & Production')], max_length=16),
        ),
    ]
