# Generated by Django 2.1.3 on 2018-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('GSP', 'Grand sponsors plus'), ('GS', 'Grand sponsors'), ('SPO', 'Sponsors'), ('SUP', 'Supporters')], max_length=2)),
                ('link', models.URLField()),
            ],
        ),
    ]
