# Generated by Django 2.1.3 on 2018-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('GSP', 'Grand sponsors plus'), ('GS', 'Grand sponsors'), ('SPO', 'Sponsors'), ('SUP', 'Supporters')], max_length=3),
        ),
    ]
