# Generated by Django 2.1.2 on 2019-03-04 11:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_untranslated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to='partners/', verbose_name='Image', width_field='image_width'),
        ),
    ]
