# Generated by Django 2.1.2 on 2019-03-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20190305_1647'),
        ('partners', '0006_auto_20190227_1203'),
    ]

    operations = [
    ]
